### ISSUE TITLE
no Height in typings, and align blow up

### ISSUE THREAD

**Issue by mi4uu** [wobsoriano/blipgloss#1]
```typescript

import { NewStyle, Position } from 'blipgloss'

const style = NewStyle()
  .Bold(true)
  .Foreground('#FAFAFA')
  .Background('#7D56F4')
  .Width(22)
  .Align(Position.Center)

console.log(style.Render('Hello'))


```

end up with:

```

$ bun run ./src/index.ts
unexpected fault address 0x41f4770400000000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x41f4770400000000 pc=0x137804bb4]

goroutine 17 [running, locked to thread]:
runtime.throw({0x137929969?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x1400014bca0 sp=0x1400014bc70 pc=0x137836560
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:842 +0x1a0 fp=0x1400014bcd0 sp=0x1400014bca0 pc=0x13784b3d0
indexbytebody()
        /usr/local/go/src/internal/bytealg/indexbyte_arm64.s:74 +0x64 fp=0x1400014bce0 sp=0x1400014bce0 pc=0x137804bb4
runtime.findnull(0x137971f00?)
        /usr/local/go/src/runtime/string.go:542 +0x7c fp=0x1400014bd40 sp=0x1400014bce0 pc=0x137850b2c
runtime.gostring(0x137971f00?)
        /usr/local/go/src/runtime/string.go:331 +0x20 fp=0x1400014bd90 sp=0x1400014bd40 pc=0x1378607b0
main._Cfunc_GoString(...)
        _cgo_gotypes.go:72
main.str(...)
        /source/main.go:28
main.getStyle(...)
        /source/main.go:37
main.Align(0x13796dd01?, 0x4fa3b820)
        /source/main.go:162 +0x28 fp=0x1400014bde0 sp=0x1400014bd90 pc=0x137926cf8
_cgoexp_13e36339c2a6_Align(0x16ef3e668?)
        _cgo_gotypes.go:250 +0x28 fp=0x1400014be00 sp=0x1400014bde0 pc=0x137927e08
runtime.cgocallbackg1(0x137927de0, 0x1400014bfe0?, 0x0)
        /usr/local/go/src/runtime/cgocall.go:316 +0x244 fp=0x1400014bef0 sp=0x1400014be00 pc=0x137805fa4
runtime.cgocallbackg(0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/cgocall.go:235 +0xd8 fp=0x1400014bf80 sp=0x1400014bef0 pc=0x137805cd8
runtime.cgocallbackg(0x137927de0, 0x16ef3e690, 0x0)
        <autogenerated>:1 +0x1c fp=0x1400014bfb0 sp=0x1400014bf80 pc=0x13786561c
runtime.cgocallback(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/asm_arm64.s:1094 +0xa0 fp=0x1400014bfe0 sp=0x1400014bfb0 pc=0x137863e90
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400014bfe0 sp=0x1400014bfe0 pc=0x137863f64

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000052fa0 sp=0x14000052f80 pc=0x137838ea4
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xb4 fp=0x14000052fd0 sp=0x14000052fa0 pc=0x137838d34
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000052fd0 sp=0x14000052fd0 pc=0x137863f64
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000053770 sp=0x14000053750 pc=0x137838ea4
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0xa4 fp=0x140000537b0 sp=0x14000053770 pc=0x137826284
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000537d0 sp=0x140000537b0 pc=0x13781a6b8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000537d0 sp=0x140000537d0 pc=0x137863f64
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x70

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1400002a0e0?, 0x137961ca0?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000053f50 sp=0x14000053f30 pc=0x137838ea4
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x137a7bc00)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x5c fp=0x14000053f80 sp=0x14000053f50 pc=0x13782424c
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x44 fp=0x14000053fb0 sp=0x14000053f80 pc=0x1378247e4
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000053fd0 sp=0x14000053fb0 pc=0x13781a658
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000053fd0 sp=0x14000053fd0 pc=0x137863f64
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xb4

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400004e580 sp=0x1400004e560 pc=0x137838ea4
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x128 fp=0x1400004e7d0 sp=0x1400004e580 pc=0x1378198d8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400004e7d0 sp=0x1400004e7d0 pc=0x137863f64
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x94
error: script "gen" exited with code 6 (SIGABRT)

```
<img width="936" alt="image" src="https://github.com/wobsoriano/blipgloss/assets/676810/0af934ac-4cbf-45f9-8cbd-04bd396a80b5">

**Comment by wobsoriano** [comment]
Fixed in 0.2.0. Thanks!
